---
apiVersion: apps/v1
kind: deployment
metadata:
  name: my-web-app
  labels:
    app: my-web-app
spec:
  replicas: 4
  selector:
    matchLabel:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
  spec:
    containers:
      - name: web-app
        image: bhargavharshith/web-app:v1
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: service
metadata:
  name: my-webapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocal: tcp
  selector:
    app: my-web-app
